project:
  type: website
  output-dir: docs

website:
  title: "Dionne Argyropoulos, PhD"  
  favicon: images/dargy_cartoon.png
  repo-url: https://github.com/dionnecargy/dionnecargy.github.io
  # google-analytics: "G-CB5M3V95HB"
  # cookie-consent: true
  navbar:
    background: "#8A88AA"
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: tools.qmd
        text: Tools
      # - href: Research
      #   menu: 
      #     - href: "Pages_CV/03_ResearchInterests.qmd"
      #       text: "Research Interests"
      #     - href: "Pages_CV/04_PublishedPapers.qmd"
      #       text: "Published Papers"
      #     - href: "Pages_CV/05_Conferences.qmd"
      #       text: "Conferences"
      # - href: Leadership, Community and Engagement
      #   menu: 
      #     - href: "Pages_CV/06_Volunteering.qmd"
      #       text: "Volunteering"
      #     - href: "Pages_CV/07_Awards.qmd"
      #       text: "Awards"
      #     - href: "Pages_CV/08_Work.qmd"
      #       text: "Work"
      # - href: Codebook
      #   menu: 
      #     - href: "code/00_code_intro.qmd"
      #       text: "Introduction"
      #     - href: "code/01_quarto.qmd"
      #       text: "Quarto"
      #     - href: "code/02_package.qmd"
      #       text: "Packages"
      #     - href: "code/03_shiny.qmd"
      #       text: "R Shiny"
      #     - href: "code/04_targets.qmd"
      #       text: "Targets"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dionneargy/
      - icon: bluesky
        href: https://bsky.app/profile/dionnecargy.bsky.social
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/dionnecargy
          - text: Report a Bug
            url:  https://github.com/dionnecargy
  page-footer: 
    left: "Copyright 2026, Dionne C. Argyropoulos"
    right: 
      - icon: github
        href: https://github.com/dionnecargy
      - icon: linkedin
        href: https://www.linkedin.com/in/dionneargy/
      - icon: bluesky
        href: https://bsky.app/profile/dionnecargy.bsky.social
  page-navigation: true
  back-to-top-navigation: true
  # sidebar:
  #   style: "docked"
  #   search: true
  #   logo: "images/dionne_cartoon.png"
  #   contents:
  #     - index.qmd
      # - section: "Research"
      #   contents: 
      #     - "Pages_CV/03_ResearchInterests.qmd"
      #     - "Pages_CV/04_PublishedPapers.qmd"
      #     - "Pages_CV/05_Conferences.qmd"
      # - section: "Leadership, Community and Engagement"
      #   contents: 
      #     - "Pages_CV/06_Volunteering.qmd"
      #     - "Pages_CV/07_Awards.qmd"
      #     - "Pages_CV/08_Work.qmd"
      # - section: "Code: The Basics"
      #   contents: 
      #     - "code/00_code_intro.qmd"
      #     - "code/01_quarto.qmd"
      #     - "code/02_package.qmd"
      #     - "code/03_shiny.qmd"
      #     - "code/04_targets.qmd"

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.css]
    css: styles.css
    body-classes: small-banner
    code-overflow: wrap
    toc: true
    fontawesome: true
    page-layout: full
    execute:
      warning: false

editor: visual

