project:
  type: website
  output-dir: docs

website:
  title: "Dionne Argyropoulos, PhD"  
  favicon: images/dargy_cartoon.png
  repo-url: https://github.com/dionnecargy/dionnecargy.github.io
  # google-analytics: "G-CB5M3V95HB"
  # cookie-consent: true
  navbar:
    background: "#8A88AA"
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: tools.qmd
        text: Tools
      - href: pages_cv/publications.qmd
        text: Publications
      - href: pages_cv/cv.qmd
        text: CV 
      - text: Codebook
        menu:
          - href: "codebook/00_code_intro.qmd"
            text: "Introduction"
          # - href: "codebook/01_quarto.qmd"
          #   text: "Quarto"
          - href: "codebook/02_package.qmd"
            text: "Creating Packages"
          # - href: "codebook/03_shiny.qmd"
          #   text: "R Shiny"
          - href: "codebook/04_targets.qmd"
            text: "Using {targets}"
          # - href: "codebook/05_popgen.qmd"
          #   text: Population Genetics
      # - text: Research
      #   menu: 
      #     - href: "pages_cv/03_ResearchInterests.qmd"
      #       text: "Research Interests"
      #     - href: "pages_cv/04_PublishedPapers.qmd"
      #       text: "Published Papers"
      #     - href: "pages_cv/05_Conferences.qmd"
      #       text: "Conferences"
      # - text: Leadership, Community and Engagement
      #   menu: 
      #     - href: "pages_cv/06_Volunteering.qmd"
      #       text: "Volunteering"
      #     - href: "pages_cv/07_Awards.qmd"
      #       text: "Awards"
      #     - href: "pages_cv/08_Work.qmd"
      #       text: "Work"
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dionneargy/
      - icon: bluesky
        href: https://bsky.app/profile/dionnecargy.bsky.social
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/dionnecargy
          - text: Report a Bug
            url:  https://github.com/dionnecargy
  page-footer: 
    left: "Copyright 2026, Dionne C. Argyropoulos"
    right: 
      - icon: github
        href: https://github.com/dionnecargy
      - icon: linkedin
        href: https://www.linkedin.com/in/dionneargy/
      - icon: bluesky
        href: https://bsky.app/profile/dionnecargy.bsky.social
  page-navigation: true
  back-to-top-navigation: true

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.css]
    css: styles.css
    body-classes: small-banner
    code-overflow: wrap
    toc: true
    fontawesome: true
    page-layout: full
    execute:
      warning: false

editor: visual
